---
## output dir
output_prefix: "output_low_res"
time_step: 0.041666
simulation_time: 20

radius:  1
init_vel_x: 0
init_vel_y: 0
init_vel_z: 0

obj-pos-x: 0
obj-pos-y: 0
obj-pos-z: 0

FLIP_domain_collision: true
FLIP_domain_solid: false
FLIP_solid_friction: 0.0
FLIPCFL: 2
FLIP_min_step_num: 1
FLIP_max_step_num: 10

FLIPpool-minx: -3
FLIPpool-miny: -0
FLIPpool-minz: -3
FLIPpool-maxx: 3
FLIPpool-maxy: 5
FLIPpool-maxz: 3
FLIPdx:  0.01

pressure_acc: 1e-4
viscosity_acc: 1e-3

enable_viscosity: true
viscosity_coef: 20000
solids_vdb: "cross_wireframe_low_res.vdb"
#solids_vel_vdb
source_vdb: "source_vdb_bunny.vdb"
#source_vel_vdb

dynamic_obj_enabled: false
dynamic_obj_folder: ""
dynamic_obj_prefix: ""

#

