---
## Options: pressure/viscosity
equation_type: "viscosity"

nx: 128

output_prefix: './benchmark'

##################################################################################
## below settings for pressure setup

## Options: sparse/compact
poisson_scene_type: compact

## pressure_solver_method
## Options:
# 0: Eigen diagonal PCG
# 1: Eigen ICPCG
# 2: Batty ICPCG
# 3: unsmooth aggregation AMG PCG
# 4: SIMD UAAMG PCG
# 5: AMGCL
pressure_solver_method: 4

## pressure_smoother, applicable for pressure_solver_method 3 & 4
## Options:
# 0: damped jacobi
# 1: Scheduled Relaxed Jacobi
# 2: Red Black Gauss Seidel
# 3： SPAI0
pressure_smoother: 2

## control sparse scene
nballs: 1000
resizer: 0.3

##################################################################################
# below settings for viscosity setup
## viscosity_solver_method
## Options:
# 0: Eigen diagonal PCG
# 1: Batty ICPCG
# 2: unsmooth aggregation AMG PCG
# 3: SIMD UAAMG PCG
# 4: AMGCL
viscosity_solver_method: 3

# viscosity solver smoother, applicable for viscosity_solver_method = 3
# Only 2 multicolor Gauss Seidel converges.
# 0: Damped Jacobi
# 1: Scheduled Relaxed Jacobi designed for Poisson
# 2: Multi Color Gauss Seidel
# 3: SPAI0 
viscosity_smoother: 2

viscosity_coef: 10000