---
## output dir
output_prefix: "dbg"
time_step: 0.041666
simulation_time: 0.2

radius:  1
init_vel_x: 0
init_vel_y: 0
init_vel_z: 0

obj-pos-x: 0
obj-pos-y: 0
obj-pos-z: 0

FLIP_domain_collision: true
FLIP_domain_solid: false
FLIP_solid_friction: 0.0
FLIPCFL: 4

FLIPpool-minx: -3
FLIPpool-miny: -0
FLIPpool-minz: -3
FLIPpool-maxx: 3
FLIPpool-maxy: 4
FLIPpool-maxz: 3
FLIPdx:  0.03

enable_viscosity: true
viscosity_coef: 1000
#solids_vdb 
#solids_vel_vdb
source_vdb: "source.vdb"
#source_vel_vdb

